// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

/*
Package gamedef is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	SessionAccepted
	SessionConnected
	SessionAcceptFailed
	SessionConnectFailed
	SessionClosed
	RemoteCallREQ
	RemoteCallACK
	TestEchoACK
*/
package gamedef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 一个连接接入
type SessionAccepted struct {
}

func (m *SessionAccepted) Reset()                    { *m = SessionAccepted{} }
func (m *SessionAccepted) String() string            { return proto.CompactTextString(m) }
func (*SessionAccepted) ProtoMessage()               {}
func (*SessionAccepted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 已连接
type SessionConnected struct {
}

func (m *SessionConnected) Reset()                    { *m = SessionConnected{} }
func (m *SessionConnected) String() string            { return proto.CompactTextString(m) }
func (*SessionConnected) ProtoMessage()               {}
func (*SessionConnected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 接受错误
type SessionAcceptFailed struct {
	Reason string `protobuf:"bytes,1,opt,name=Reason" json:"Reason,omitempty"`
}

func (m *SessionAcceptFailed) Reset()                    { *m = SessionAcceptFailed{} }
func (m *SessionAcceptFailed) String() string            { return proto.CompactTextString(m) }
func (*SessionAcceptFailed) ProtoMessage()               {}
func (*SessionAcceptFailed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SessionAcceptFailed) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// 连接错误
type SessionConnectFailed struct {
	Reason string `protobuf:"bytes,1,opt,name=Reason" json:"Reason,omitempty"`
}

func (m *SessionConnectFailed) Reset()                    { *m = SessionConnectFailed{} }
func (m *SessionConnectFailed) String() string            { return proto.CompactTextString(m) }
func (*SessionConnectFailed) ProtoMessage()               {}
func (*SessionConnectFailed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SessionConnectFailed) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// 连接断开
type SessionClosed struct {
	Reason string `protobuf:"bytes,1,opt,name=Reason" json:"Reason,omitempty"`
}

func (m *SessionClosed) Reset()                    { *m = SessionClosed{} }
func (m *SessionClosed) String() string            { return proto.CompactTextString(m) }
func (*SessionClosed) ProtoMessage()               {}
func (*SessionClosed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SessionClosed) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// 请求
type RemoteCallREQ struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID" json:"CallID,omitempty"`
}

func (m *RemoteCallREQ) Reset()                    { *m = RemoteCallREQ{} }
func (m *RemoteCallREQ) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallREQ) ProtoMessage()               {}
func (*RemoteCallREQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoteCallREQ) GetMsgID() uint32 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *RemoteCallREQ) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoteCallREQ) GetCallID() int64 {
	if m != nil {
		return m.CallID
	}
	return 0
}

// 回应
type RemoteCallACK struct {
	MsgID  uint32 `protobuf:"varint,1,opt,name=MsgID" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	CallID int64  `protobuf:"varint,3,opt,name=CallID" json:"CallID,omitempty"`
}

func (m *RemoteCallACK) Reset()                    { *m = RemoteCallACK{} }
func (m *RemoteCallACK) String() string            { return proto.CompactTextString(m) }
func (*RemoteCallACK) ProtoMessage()               {}
func (*RemoteCallACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoteCallACK) GetMsgID() uint32 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *RemoteCallACK) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoteCallACK) GetCallID() int64 {
	if m != nil {
		return m.CallID
	}
	return 0
}

// ==========================================================
// 测试用消息
// ==========================================================
type TestEchoACK struct {
	Content  string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
	Content2 string `protobuf:"bytes,2,opt,name=Content2" json:"Content2,omitempty"`
}

func (m *TestEchoACK) Reset()                    { *m = TestEchoACK{} }
func (m *TestEchoACK) String() string            { return proto.CompactTextString(m) }
func (*TestEchoACK) ProtoMessage()               {}
func (*TestEchoACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TestEchoACK) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TestEchoACK) GetContent2() string {
	if m != nil {
		return m.Content2
	}
	return ""
}

func init() {
	proto.RegisterType((*SessionAccepted)(nil), "gamedef.SessionAccepted")
	proto.RegisterType((*SessionConnected)(nil), "gamedef.SessionConnected")
	proto.RegisterType((*SessionAcceptFailed)(nil), "gamedef.SessionAcceptFailed")
	proto.RegisterType((*SessionConnectFailed)(nil), "gamedef.SessionConnectFailed")
	proto.RegisterType((*SessionClosed)(nil), "gamedef.SessionClosed")
	proto.RegisterType((*RemoteCallREQ)(nil), "gamedef.RemoteCallREQ")
	proto.RegisterType((*RemoteCallACK)(nil), "gamedef.RemoteCallACK")
	proto.RegisterType((*TestEchoACK)(nil), "gamedef.TestEchoACK")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x40, 0x59, 0xab, 0xad, 0x1d, 0x5d, 0xd4, 0x58, 0x24, 0x78, 0x5a, 0xf6, 0xe2, 0x5e, 0xec,
	0x41, 0xbf, 0xa0, 0x64, 0x2b, 0x14, 0xf1, 0xd0, 0xd1, 0x1f, 0x88, 0xd9, 0xb1, 0x16, 0xd2, 0x4c,
	0x69, 0xf2, 0xff, 0x48, 0x62, 0x56, 0xd8, 0x8b, 0x5e, 0xbc, 0xcd, 0x1b, 0x5e, 0x1e, 0x84, 0x01,
	0x30, 0x7c, 0xa0, 0xf9, 0xfe, 0xc0, 0x81, 0xc5, 0x64, 0xa3, 0x77, 0xd4, 0xd1, 0x47, 0x7d, 0x05,
	0x17, 0xaf, 0xe4, 0xfd, 0x96, 0xdd, 0xc2, 0x18, 0xda, 0x07, 0xea, 0x6a, 0x01, 0x97, 0x79, 0xa5,
	0xd8, 0x39, 0x32, 0x71, 0x77, 0x0f, 0xd7, 0x03, 0xed, 0x49, 0x6f, 0x2d, 0x75, 0xe2, 0x06, 0xc6,
	0x48, 0xda, 0xb3, 0x93, 0x45, 0x55, 0x34, 0x53, 0xcc, 0x54, 0xcf, 0x61, 0x36, 0x4c, 0xfc, 0xe1,
	0xdf, 0x41, 0xd9, 0xfb, 0x96, 0xfd, 0x2f, 0xe2, 0x1a, 0x4a, 0xa4, 0x1d, 0x07, 0x52, 0xda, 0x5a,
	0x5c, 0xae, 0xc5, 0x0c, 0x4e, 0x5e, 0xfc, 0x66, 0xd5, 0x26, 0xaf, 0xc4, 0x6f, 0x10, 0x02, 0x8e,
	0x5b, 0x1d, 0xb4, 0x3c, 0xaa, 0x8a, 0xe6, 0x1c, 0xd3, 0x1c, 0x93, 0xf1, 0xd1, 0xaa, 0x95, 0xa3,
	0xaa, 0x68, 0x46, 0x98, 0x69, 0x98, 0x5c, 0xa8, 0xe7, 0x7f, 0x48, 0x2a, 0x38, 0x7b, 0x23, 0x1f,
	0x96, 0xe6, 0x93, 0x63, 0x50, 0xc2, 0x44, 0xb1, 0x0b, 0xe4, 0x42, 0xfe, 0x4d, 0x8f, 0xe2, 0x16,
	0x4e, 0xf3, 0xf8, 0x90, 0xc2, 0x53, 0xfc, 0xe1, 0xf7, 0x71, 0xba, 0xd4, 0xe3, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x72, 0xf5, 0x0e, 0x3e, 0xb7, 0x01, 0x00, 0x00,
}
